### ISSUE TITLE
Foreign Keys and Table order

### ISSUE THREAD

**Issue by neokeats** [AnatolyUss/FromMySqlToPostgreSql#55] opened 2016-12-20 16:58 UTC
hi, 
i had a lot of tables to import with a lot of foreign keys.
i couldn't import them because the table orders can't be controlled or i didn't found how. 
most of the datas couldn't be imported because the data they were referring datas that were created after them. 

i found a workaround : 
changing line 1256 of migration/FromMySqlToPostgreSql/FromMySqlToPostgreSql.php
from :
 `
.  implode(',', $arrPKs) . ') ON UPDATE ' . $strUpdateRule . ' ON DELETE ' . $strDeleteRule . ';';
`
to: 
`
.  implode(',', $arrPKs) . ') ON UPDATE ' . $strUpdateRule . ' ON DELETE ' . $strDeleteRule . ' DEFERRABLE;';
`

Adding DEFERRABLE makes postgresql check the foreign keys integrity only at the end of the transaction so everything was migrated correctly.

Maybe there is a better way ? 

thanks.

**Comment by mr-russ** [comment] 2017-05-06 05:15
I'm confused about how this was the case.  All foreign key constraints are added after all data is loaded.  So how did you get into this state, what was the initial setup?

**Comment by AnatolyUss** [comment] 2017-05-06 06:54
Please, provide us with log files (zipped) , if possible.
It will let us see the exact order of actions.

**Comment by mr-russ** [comment] 2017-05-10 10:10
I would request that this be closed as can't reproduce.  We don't have logs and I can't see how this situation would arise unless you are only importing data.  Which wouldn't run the foreign key code anyway.

**Comment by AnatolyUss** [comment] 2017-05-12 15:48
Agree.

**Closed by AnatolyUss** 2017-05-12 15:48 UTC
