### ISSUE TITLE
longblob type does not convert

### ISSUE THREAD

**Issue by LennyLip** [AnatolyUss/FromMySqlToPostgreSql#57] opened 2017-02-13 05:39 UTC
type "longblob" does not exist

https://en.wikibooks.org/wiki/Converting_MySQL_to_PostgreSQL

BINARY(n)
VARBINARY(n)
TINYBLOB
BLOB
MEDIUMBLOB
LONGBLOB

must convert to BYTEA ?

**Comment by LennyLip** [comment] 2017-02-13 06:39
some links 
http://stackoverflow.com/questions/26990559/convert-mysql-binary-to-postgresql-bytea

**Comment by AnatolyUss** [comment] 2017-02-15 21:38
Hello,
Conversion of all kind of blobs to bytea should work.
Please, send me the <code>/FromMySqlToPostgreSql/logs_directory/errors-only.log</code> file.
Thanks

**Comment by mr-russ** [comment] 2017-05-06 09:26
I have added a test case for migrating a longblob and it successfully migrates.  Without more information on the case of this, it's going to have to be closed as can't reproduce.

If you could post a reproduction case or the Loh files that would allow further investigation.

**Comment by mr-russ** [comment] 2017-05-06 10:17
I have found that there appears to be a problem with the content conversion of bytea fields, they don't contain the correct data after migration.  It appears to be a double escaping issue, mixed with not importing correctly after the most recent pull request merge.  I'm not clear if it was still and issue before that.  I'm testing a fix and will put up a pull request soon.

**Comment by mr-russ** [comment] 2017-05-12 03:56
Known issues with longblob are resolved in #64

**Closed** 2017-05-12 15:49 UTC
